### PR TITLE
Reservation validation

### PR DESCRIPTION
**Pull request by bo-quan**
#### What does this PR do?
Simplify reservation creation using mac instead of machine name.

#### Do you have any concerns with this PR?
No

#### How can the reviewer verify this PR?
Run snaps-boot ci in lab3 or against bare metal.

#### Any background context you want to provide?
No

#### Questions:
- Have you connected this PR to the issue it resolves?
#201 
- Does the documentation need an update?
No
- Does this add new Python dependencies?
No
- Have you added unit or functional tests for this PR?
No
- Does this patch update any configuration files?
No

### CODE REVIEW

**Comment by bo-quan** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by bo-quan** [comment]
Run Tests

**Comment by bo-quan** [comment]
Run Tests

**Comment by bo-quan** [comment]
Run Tests

**Comment by bo-quan** [comment]
Run Tests

**Pull request merged**
