### PR TITLE
Fix ci scripts

### PR DESCRIPTION
**Pull request by skulasekar**
#### What does this PR do?
Corrects CI scripts to:
- Use metadata for flavors
- Work with different names of source directory

#### Do you have any concerns with this PR?
No.

#### How can the reviewer verify this PR?
Run CI scripts

#### Questions:
- Have you connected this PR to the issue it resolves?
No
- Does the documentation need an update?
Yes
- Does this add new Python dependencies?
No
- Have you added unit or functional tests for this PR?
No
- Does this patch update any configuration files?
Yes.  The snaps CI env file.

### CODE REVIEW

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Pull request merged**
