### PR TITLE
Injects key into build server root user when iaas_launch.py is executed as a sudo user

### LINKED ISSUE #203: Add support for sudo users to create an ssh key for the root user.
When snaps-boot is run by a sudo user, ensure a key is generated that will allow passwordless access to the node's root account from the build server.

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #203 
Ensures that the build server's root user has an ssh key injected when iaas_launch.py is started by a non-root sudo user.
Added apt-cacher-ng installation prior to DRP install
Added additional CI validation to ensure provisioned nodes can install via apt.

#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
run CI as root and as the standard sudo user 'ubuntu' using the new CI configuration flag 'run_as_root'
#### Any background context you want to provide?
The way master is currently is that a sudo user cannot execute the iaas_launch.py script as when this was originally introduced, it caused issues with snaps-openstack as that project still requires to be executed by the root user on the build server. This change creates and injects the same ssh generated key for both the sudo and root users allowing both to obtain passwordless ssh access to the nodes being provisioned
#### Questions:
- Have you connected this PR to the issue it resolves?
yes
- Does the documentation need an update?
no
- Does this add new Python dependencies?
No, it actually removes paramiko
- Have you added unit or functional tests for this PR?
Updated CI scripts to handle both scenarios
- Does this patch update any configuration files?
no

### CODE REVIEW

**Comment by skulasekar** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
@bo-quan - looks like CI was hacking due to OpenStack lab 3 resources. Ubuntu passed!

**Comment by spisarski** [comment]
@Sanjhana-Jayagopal or @RandyLevensalor - This PR is now complete, can either or you please review? I would like to get this merged today or tomorrow.

**Pull request merged**
