### PR TITLE
Ci refactor

### LINKED ISSUE #284: Speed up CI
Use pre-build libvirt AMI rather than building each time

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #284 
Speeds up CI by using a pre-built image with libvirt and all VMs necessary running.
#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
run ci
#### Questions:
- Have you connected this PR to the issue it resolves?
yes
- Does the documentation need an update?
no
- Does this add new Python dependencies?
no
- Have you added unit or functional tests for this PR?
n/a
- Does this patch update any configuration files?
no

### CODE REVIEW

**Comment by spisarski** [comment]
Note, this PR already has the changes to PR #282 merged into it

**Comment by spisarski** [comment]
Please review so we can merge soon to help complete changes downstream

**Comment by spisarski** [comment]
Double-edged sword. By 'fixing' CI, I must break it first.
@bo-quan - Please reconfigure the Jenkins job with the snaps-common boot-env.tfvars file in the 
aws_ci branch.

So make sure https://github.com/cablelabs/snaps-common/pull/10 is merged prior to this PR

**Comment by bo-quan** [comment]
Run Tests

**Comment by bo-quan** [comment]
Run Tests

**Comment by bo-quan** [comment]
Run Tests

**Comment by bo-quan** [comment]
Run Tests

**Comment by bo-quan** [comment]
Run Tests

**Pull request merged**
