### PR TITLE
Digital rebar backend update

### PR DESCRIPTION
**Pull request by RandyLevensalor**
#### Questions:
- Have you connected this PR to the issue it resolves?
- Does the documentation need an update?
- Does this add new Python dependencies?
- Have you added unit or functional tests for this PR?
- Does this patch update any configuration files?

### CODE REVIEW

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
Rescinding my approval due to CI failures but I guess I can't officially do that now.

**Comment by bo-quan** [comment]
Run Tests

**Pull request merged**
