### PR TITLE
50-cloud-init-issue

### PR DESCRIPTION
**Pull request by mansi-jain2**
#### What does this PR do?
This PR removes 50-cloud-init.cfg file
#### Do you have any concerns with this PR?
No
#### How can the reviewer verify this PR?
By OS_Provisioning
#### Any background context you want to provide?
No
#### Screenshots or logs (if appropriate)
NA
#### Questions:
- Have you connected this PR to the issue it resolves?
188 (snaps-openstack)
- Does the documentation need an update?
No
- Does this add new Python dependencies?
No
- Have you added unit or functional tests for this PR?
No
- Does this patch update any configuration files?
No

### CODE REVIEW

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by bo-quan** [comment]
During today's discussion, we may want to re-open this issue as cloud-init is needed to set up ssh key for vms and bare metal servers.  We cannot simply disable cloud-init.

**Comment by mansi-jain2** [comment]
We are able to setup ssh keys even after removing 50-cloud-init.cfg responsible for network configuration.
50-cloud-init.cfg file is generated by cloud-init by default for network configuration.
To disable cloud-init's network configuration capabilities, we need to write a file /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

**Comment by mansi-jain2** [comment]
We are able to setup ssh keys even after removing 50-cloud-init.cfg responsible for network configuration.
50-cloud-init.cfg file is generated by cloud-init by default for network configuration.
To disable cloud-init's network configuration capabilities, we need to write a file /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

**Comment by mansi-jain2** [comment]
We are able to setup ssh keys even after removing 50-cloud-init.cfg responsible for network configuration.
50-cloud-init.cfg file is generated by cloud-init by default for network configuration.
To disable cloud-init's network configuration capabilities, we need to write a file /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

**Comment by mansi-jain2** [comment]
The fix just disable network configuration injected by default when cloud init is used. The fix just disbales the networking part, ssh keys are still copied by cloud init.
The old fix is still valid

**Comment by bo-quan** [comment]
Thanks @mansi-jain2 for your clarification. I'll move this issue and #148 to closed then.

**Pull request merged**
