### PR TITLE
Cleaned up the prerequisites

### PR DESCRIPTION
**Pull request by Sanjhana-Jayagopal**
#### What does this PR do?

- Installation through requirements.txt rather than prerequisites.sh
- Package installs for apt-cacher-ng, ipmitool and sshpass have to be moved to the playbooks that require them.

#### Questions:
- Have you connected this PR to the issue it resolves?
- Does the documentation need an update?
- Does this add new Python dependencies?
- Have you added unit or functional tests for this PR?

### CODE REVIEW

**Comment by spisarski** [comment]
@RandyLevensalor, plans are to get rid of this script completely and document the environment setup. Ultimately, installation should simply become: pip install snaps-boot and really nothing else. The same pattern should be applied to snaps-openstack and snaps-kubernetes.

**Comment by RandyLevensalor** [comment]
@spisarski I agree on the direction.  Until we can eliminate the preRequsite.sh script, I would prefer not to complicate the install process by adding another step.

If we must add another step, then it needs to be added in the user's guide.

**Comment by spisarski** [comment]
The next patch will hopefully remove sshpass

**Comment by spisarski** [comment]
@RandyLevensalor, great points.
@Sanjhana-Jayagopal, I agree that the pip install should be added to PreRequisites.sh for now and we can have a discussion on whether or not to simply document the build server setup or keep the end-user responsibilities as-is. I prefer the documentation approach as I would rather see the server's owner decide on how they want the python runtime to be setup (default or virtual) but we can vote on that later.

Sorry, I should not have thought about the end-user ;)

**Pull request merged**
